---
# Home Server Services
- Home Server:
    - AdGuard Home:
        icon: adguard-home.png
        href: https://adguard.{{HOMEPAGE_VAR_DOMAIN}}
        description: Network-wide ad blocking
        widget:
          type: adguard
          url: http://adguard-home
          username: {{HOMEPAGE_VAR_ADGUARD_USER}}
          password: {{HOMEPAGE_VAR_ADGUARD_PASS}}

    - n8n:
        icon: n8n.png
        href: https://n8n.{{HOMEPAGE_VAR_DOMAIN}}
        description: Workflow automation
        container: n8n

    - Wireguard VPN:
        icon: wireguard.png
        href: https://wireguard.{{HOMEPAGE_VAR_DOMAIN}}
        description: VPN server management
        container: wireguard

    - Prometheus:
        icon: prometheus.png
        href: https://prometheus.{{HOMEPAGE_VAR_DOMAIN}}
        description: Metrics & alerting
        widget:
          type: prometheus
          url: http://prometheus:9090

    - Alertmanager:
        icon: alertmanager.png
        href: https://alertmanager.{{HOMEPAGE_VAR_DOMAIN}}
        description: Alert management
        container: alertmanager

    - Traefik:
        icon: traefik.png
        href: https://traefik.{{HOMEPAGE_VAR_DOMAIN}}
        description: Reverse proxy management
        container: traefik

    - Grafana:
        icon: grafana.png
        href: https://grafana.{{HOMEPAGE_VAR_DOMAIN}}
        description: Monitoring dashboards
        widget:
          type: grafana
          url: http://grafana:3000
          username: {{HOMEPAGE_VAR_GRAFANA_USER}}
          password: {{HOMEPAGE_VAR_GRAFANA_PASS}}

# Calendar & Tasks section
- Calendar & Tasks:
    - BOM Weather:
        icon: mdi-weather-partly-cloudy
        href: http://www.bom.gov.au/
        description: Australian weather forecast
        widget:
          type: customapi
          url: http://homepage-api:5000/api/bom/weather
          refreshInterval: 300000  # 5 minutes
          mappings:
            - field: observations.temp
              label: Temperature
              suffix: "°C"
            - field: observations.temp_feels_like
              label: Feels Like
              suffix: "°C"
            - field: observations.humidity
              label: Humidity
              suffix: "%"
            - field: forecast_daily.0.short_text
              label: Today
