---
# Life - calendar, weather, etc
- Today:
    - BOM Weather:
        icon: mdi-weather-partly-cloudy
        href: http://www.bom.gov.au/
        description: Australian weather forecast
        widget:
          type: customapi
          url: http://homepage-api:5000/api/bom/weather
          refreshInterval: 300000  # 5 minutes
          mappings:
            - field: observations.temp
              label: Temperature
              suffix: "°C"
            - field: observations.temp_feels_like
              label: Feels Like
              suffix: "°C"
            - field: observations.humidity
              label: Humidity
              suffix: "%"
            - field: forecast_daily.0.short_text
              label: Today

    - Google Calendar:
        icon: google-calendar.png
        href: https://calendar.google.com
        description: Upcoming events
        widget:
          type: calendar
          integrations:
            - type: ical
              url: {{HOMEPAGE_VAR_GCAL_ICAL_URL}}
              name: Personal Calendar
              color: blue
              maxEvents: 5

# Transport & Commute - Public transport and traffic
- Transport & Commute:
    - Train Departures:
        icon: {{HOMEPAGE_VAR_TRANSPORT_STOP_1_ICON}}
        description: {{HOMEPAGE_VAR_TRANSPORT_STOP_1_NAME}}
        widget:
          type: customapi
          url: http://homepage-api:5000/api/transport/departures/{{HOMEPAGE_VAR_TRANSPORT_STOP_1_ID}}
          refreshInterval: 60000  # 1 minute
          mappings:
            - field: departures.0.destination
              label: Next Train
            - field: departures.0.time
              label: Departs
              format: relativeDate
            - field: departures.1.time
              label: Following
              format: relativeDate

    - Bus Departures:
        icon: {{HOMEPAGE_VAR_TRANSPORT_STOP_2_ICON}}
        description: {{HOMEPAGE_VAR_TRANSPORT_STOP_2_NAME}}
        widget:
          type: customapi
          url: http://homepage-api:5000/api/transport/departures/{{HOMEPAGE_VAR_TRANSPORT_STOP_2_ID}}
          refreshInterval: 60000
          mappings:
            - field: departures.0.destination
              label: Next Bus
            - field: departures.0.time
              label: Departs
              format: relativeDate

    - Morning Commute:
        icon: mdi-car
        description: {{HOMEPAGE_VAR_TRAFFIC_ROUTE_1_NAME}}
        widget:
          type: customapi
          url: http://homepage-api:5000/api/traffic/route?origin={{HOMEPAGE_VAR_TRAFFIC_ROUTE_1_ORIGIN}}&destination={{HOMEPAGE_VAR_TRAFFIC_ROUTE_1_DESTINATION}}
          refreshInterval: 300000  # 5 minutes
          mappings:
            - field: travelTimeMinutes
              label: Drive Time
              suffix: " min"
            - field: trafficDelayMinutes
              label: Delay
              suffix: " min"
            - field: status
              label: Traffic

    - Evening Commute:
        icon: mdi-home-import-outline
        description: {{HOMEPAGE_VAR_TRAFFIC_ROUTE_2_NAME}}
        widget:
          type: customapi
          url: http://homepage-api:5000/api/traffic/route?origin={{HOMEPAGE_VAR_TRAFFIC_ROUTE_2_ORIGIN}}&destination={{HOMEPAGE_VAR_TRAFFIC_ROUTE_2_DESTINATION}}
          refreshInterval: 300000
          mappings:
            - field: travelTimeMinutes
              label: Drive Time
              suffix: " min"
            - field: trafficDelayMinutes
              label: Delay
              suffix: " min"
            - field: status
              label: Traffic

    - Transport NSW:
        icon: mdi-bus-multiple
        href: https://transportnsw.info/
        description: View all services

# Core Services - Primary user-facing services that "do stuff"
- Services:
  - Core Services:
      - AdGuard Home:
          icon: adguard-home.png
          href: https://adguard.{{HOMEPAGE_VAR_DOMAIN}}
          description: Network-wide ad blocking
          widget:
            type: adguard
            url: http://adguard-home
            username: {{HOMEPAGE_VAR_ADGUARD_USER}}
            password: {{HOMEPAGE_VAR_ADGUARD_PASS}}
          container: adguard-home
          server: my-docker
          showStats: true

      - n8n:
          icon: n8n.png
          href: https://n8n.{{HOMEPAGE_VAR_DOMAIN}}
          description: Workflow automation
          container: n8n
          server: my-docker
          showStats: true

  # Monitoring Stack - Metrics collection and visualization
  - Monitoring:
      - Prometheus:
          icon: prometheus.png
          href: https://prometheus.{{HOMEPAGE_VAR_DOMAIN}}
          description: Metrics & alerting
          widget:
            type: prometheus
            url: http://prometheus:9090
          container: prometheus
          server: my-docker
          showStats: true

      - Grafana:
          icon: grafana.png
          href: https://grafana.{{HOMEPAGE_VAR_DOMAIN}}
          description: Monitoring dashboards
          widget:
            type: grafana
            url: http://grafana:3000
            username: {{HOMEPAGE_VAR_GRAFANA_USER}}
            password: {{HOMEPAGE_VAR_GRAFANA_PASS}}
          container: grafana
          server: my-docker
          showStats: true

      - Alertmanager:
          icon: alertmanager.png
          href: https://alerts.{{HOMEPAGE_VAR_DOMAIN}}
          description: Alert management
          container: alertmanager
          server: my-docker
          showStats: true

      - Node Exporter:
          icon: mdi-server
          description: System metrics exporter
          container: node-exporter
          server: my-docker
          showStats: true

      - cAdvisor:
          icon: mdi-docker
          description: Container metrics exporter
          container: cadvisor
          server: my-docker
          showStats: true

  # Dashboard Services - Homepage dashboard and backend
  - Dashboard:
      - Homepage API:
          icon: mdi-api
          description: Backend API for custom widgets
          container: homepage-api
          server: my-docker
          showStats: true

  # Network & Security - Infrastructure services for routing, VPN, and security
  - Network & Security:
      - Traefik:
          icon: traefik.png
          href: https://traefik.{{HOMEPAGE_VAR_DOMAIN}}
          description: Reverse proxy management
          widget:
            type: traefik
            url: http://traefik:8080
          container: traefik
          server: my-docker
          showStats: true

      - Wireguard VPN:
          icon: wireguard.png
          href: https://wireguard.{{HOMEPAGE_VAR_DOMAIN}}
          description: VPN server management
          container: wireguard
          server: my-docker
          showStats: true

      - Fail2ban:
          icon: mdi-shield-lock
          description: Intrusion prevention system
          container: fail2ban
          server: my-docker
          showStats: true
