---
title: Home Server Dashboard
favicon: homepage.png

# Background configuration
background:
  image: https://images.unsplash.com/photo-1557683316-973673baf926
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50

theme: dark
color: slate

# Layout configuration
layout:
  Home Server:
    style: row
    columns: 4
  Calendar & Tasks:
    style: row
    columns: 2

# UI preferences
#statusStyle: "dot"
showStats: true
hideVersion: true

# Quick launch
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false

# Header style
headerStyle: boxed
target: _blank
