---
# Top bar widgets
- logo:
    icon: mdi-shield-home

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: false

# System resources
- resources:
    label: Server
    cpu: true
    cputemp: true
    units: metric
    memory: true
    uptime: true
    # Note: disk monitoring removed - doesn't work reliably with Docker bind mounts
