# Home Assistant Configuration
default_config:

# Text to speech
tts:
  - platform: google_translate

# Automation configuration
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# HTTP Configuration
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 172.16.0.0/12  # Docker bridge networks
    - 192.168.0.0/16  # Local network range

# Recorder - limit database size
recorder:
  purge_keep_days: 30
  commit_interval: 30

# Logger
logger:
  default: info

# Zones
zone:
  - name: Home
    latitude: -33.8000
    longitude: 151.0000
    radius: 100
    icon: mdi:home

  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 200
    icon: mdi:office-building
