global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'adguard'
    static_configs:
      - targets: ['adguard:3000']
    metrics_path: '/control/stats'

  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:5678']
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']