#!/bin/bash
# configure-traefik-file-provider.sh
# Configures Traefik to use file provider for Let's Encrypt certificates
#
# This script creates a Traefik dynamic configuration file that tells Traefik
# to use the certificates generated by certbot instead of its built-in ACME.

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "Configuring Traefik File Provider for Certificates"
echo "==================================================="
echo ""

# Load environment variables
if [ -f .env ]; then
    set -a
    source .env
    set +a
else
    echo -e "${RED}ERROR: .env file not found!${NC}"
    exit 1
fi

if [ -z "$DOMAIN" ]; then
    echo -e "${RED}ERROR: DOMAIN not set in .env file${NC}"
    exit 1
fi

CONFIG_DIR="./config/traefik"
DYNAMIC_CONFIG="$CONFIG_DIR/dynamic-certs.yml"
CERT_PATH="/certs/$DOMAIN"

# Create config directory
mkdir -p "$CONFIG_DIR"

# Check if certificates exist
if [ ! -f "./data/traefik/certs/$DOMAIN.crt" ]; then
    echo -e "${RED}ERROR: Certificate not found at ./data/traefik/certs/$DOMAIN.crt${NC}"
    echo "Please run ./scripts/copy-certs-to-traefik.sh first"
    exit 1
fi

# Create dynamic configuration file
echo "Creating Traefik dynamic configuration..."
cat > "$DYNAMIC_CONFIG" <<EOF
# Traefik Dynamic Configuration - TLS Certificates
# Generated by configure-traefik-file-provider.sh on $(date)
#
# This configuration tells Traefik to use certificates generated by certbot
# instead of the built-in ACME/Let's Encrypt integration.

tls:
  certificates:
    # Wildcard certificate for *.$DOMAIN and $DOMAIN
    - certFile: $CERT_PATH.crt
      keyFile: $CERT_PATH.key
      stores:
        - default

  stores:
    default:
      defaultCertificate:
        certFile: $CERT_PATH.crt
        keyFile: $CERT_PATH.key
EOF

echo -e "${GREEN}✓${NC} Configuration file created: $DYNAMIC_CONFIG"
echo ""
echo "Configuration content:"
cat "$DYNAMIC_CONFIG"
echo ""
echo -e "${GREEN}Setup complete!${NC}"
echo ""
echo "Next steps:"
echo "  1. Restart Traefik to load the new configuration:"
echo "     sudo docker compose restart traefik"
echo ""
echo "  2. Verify certificate is loaded:"
echo "     sudo docker compose logs traefik | grep -i tls"
echo ""
echo "  3. Test HTTPS access:"
echo "     https://$DOMAIN"
echo "     https://n8n.$DOMAIN"
echo ""
